name: Build and Deploy OCI Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: francois2metz/steampipe-plugin-build-push-action@v0
