# This workflow will build a steampipe plugin image and publish it to GitHub Packages

name: Build and Deploy OCI Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: francois2metz/steampipe-plugin-build-push-action@8322715616e18efb3c1a463dcd2d1b823a9cde85
